site_name: OFS
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
# Page tree
nav:
  - Welcome: index.md
  - Stratix 10 OFS Hardware Docs:
    - Quick Start Evaluation Guide: hw/d5005/user_guides/ug_eval_ofs_d5005/ug_eval_script_ofs_d5005.md
    - Getting Started: hw/d5005/user_guides/ug_qs_ofs_d5005/ug_qs_ofs_d5005.md
    - Software Reference Manual: hw/common/reference_manual/ofs_sw/mnl_sw_ofs.md
    - FPGA Interface Manager Technical Reference Manual: hw/d5005/reference_manuals/ofs_fim/mnl_fim_ofs_d5005.md
    - FPGA Interface Manager Developer Guide: hw/d5005/dev_guides/fim_dev/ug_dev_fim_ofs_d5005.md
    - AFU Developer Guide: hw/d5005/dev_guides/afu_dev/ug_dev_afu_d5005.md
    
  
