site_name: OFS
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
# Page tree
nav:
  - Welcome: index.md
  - Stratix 10 OFS Hardware Docs:
    - Quick Start Evaluation Guide: hw/d5005/user_guides/ug_eval_ofs_d5005/ug_eval_script_ofs_d5005.md
    - Getting Started: hw/d5005/user_guides/ug_qs_ofs_d5005/ug_qs_ofs_d5005.md
    - Software Reference Manual: hw/common/reference_manual/ofs_sw/mnl_sw_ofs.md
    - FPGA Interface Manager Technical Reference Manual: hw/d5005/reference_manuals/ofs_fim/mnl_fim_ofs_d5005.md
    - FPGA Interface Manager Developer Guide: hw/d5005/dev_guides/fim_dev/ug_dev_fim_ofs_d5005.md
    - AFU Developer Guide: hw/d5005/dev_guides/afu_dev/ug_dev_afu_d5005.md
  - OFS Software Docs:
    -OPAE Installation Guide: sw/latest/docs/install_guide/installation_guide.html
    -OPAE C API Programming Guide: sw/latest/docs/fpga_api/prog_guide/readme.html
    -Building OPAE SDK Artifacts: sw/latest/docs/build_chain/fpga_api/api_build.html
    -OPAE C API Reference: sw/latest/docs/fpga_api/fpga_api.html
    -OPAE C++ Core API Reference: sw/latest/docs/fpga_api/fpga_cxx_api.html
    -OPAE Python API Reference: sw/latest/docs/fpga_api/fpga_python_api.html
    -Plugin Developer's Guide: sw/latest/docs/fpga_api/plug_guide/readme.html
    -OPAE Linux Device Driver Architecture: sw/latest/docs/drv_arch/drv_arch.html
    -OPAE tools:
      -fpgaconf: sw/latest/docs/fpga_tools/fpgaconf/fpgaconf.html
      -fpgad: sw/latest/docs/fpga_tools/fpgad/fpgad.html
      -fpgadiag: sw/latest/docs/fpga_tools/fpgadiag/README.html
      -fpgainfo: sw/latest/docs/fpga_tools/fpgainfo/fpgainfo.html
      -fpgasupdate: sw/latest/docs/fpga_tools/fpgasupdate/fpgasupdate.html
      -mmlink: sw/latest/docs/fpga_tools/mmlink/mmlink.html
      -packager: sw/latest/docs/fpga_tools/packager/packager.html
      -userclk: sw/latest/docs/fpga_tools/userclk/userclk.html
      -hssi: sw/latest/docs/fpga_tools/hssi/hssi.html
      -opaevfio: sw/latest/docs/fpga_tools/opaevfio/opaevfio.html
      -pci_device: sw/latest/docs/fpga_tools/pci_device/pci_device.html
      -opae.io: sw/latest/docs/fpga_tools/opae.io/opae.io.html
      -host_exerciser: sw/latest/docs/fpga_tools/host_exerciser/host_exerciser.html
      -hssistats: sw/latest/docs/fpga_tools/hssi_ethernet/hssistats.html
      -hssimac: sw/latest/docs/fpga_tools/hssi_ethernet/hssimac.html
      -hssiloopback: sw/latest/docs/fpga_tools/hssi_ethernet/hssiloopback.html
      -rsu: sw/latest/docs/fpga_tools/rsu/rsu.html
      -mem_tg: sw/latest/docs/fpga_tools/mem_tg/mem_tg.html
      -vabtool: sw/latest/docs/fpga_tools/vabtool/vabtool.html

  
