site_name: OFS 
repo_url: https://github.com/ofs
repo_name: ofs
theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search:
      lang: en
  # - mkdoxy:
  #     projects:
  #       opae-code:
  #         src-dirs: "docs/sw"
  #         full-doc: True
  #         doxy-cfg:
  #           FILE_PATTERNS: "*.c *.cc *.cxx *.cpp *.c++ *.java *.h *.hh *.hxx *.hpp *.h++ *.xpm"
  #           RECURSIVE: True
  #           DOXYFILE_ENCODING: "UTF-8"
  #           PROJECT_NAME: "OPAE C API"
  #           OPTIMIZE_OUTPUT_FOR_C: True
  #           EXTRACT_ALL: True
  #           EXCLUDE_SYMLINKS: True
  #           EXCLUDE_PATTERNS: "*/archive/* */.git/*"

# Page tree
nav:
  - Welcome: index.md
  - Stratix 10 OFS Hardware Docs:
      - Quick Start Evaluation Guide: 'hw/d5005/user_guides/ug_eval_ofs_d5005/ug_eval_script_ofs_d5005.md'
      - Getting Started: 'hw/d5005/user_guides/ug_qs_ofs_d5005/ug_qs_ofs_d5005.md'
      - Software Reference Manual: 'hw/common/reference_manual/ofs_sw/mnl_sw_ofs.md'
      - FPGA Interface Manager Technical Reference Manual: 'hw/d5005/reference_manuals/ofs_fim/mnl_fim_ofs_d5005.md'
      - FPGA Interface Manager Developer Guide: 'hw/d5005/dev_guides/fim_dev/ug_dev_fim_ofs_d5005.md'
      - AFU Developer Guide: 'hw/d5005/dev_guides/afu_dev/ug_dev_afu_d5005.md'
  - OFS Software:
    - OPAE USER GUIDES:
       - Quick Start Guide: sw/fpga_api/quick_start/readme.md
       - OPAE Installation Guide: sw/install_guide/installation_guide.md
       - OPAE C API Programming Guide: sw/fpga_api/prog_guide/readme.md
       - OPAE Python Bindings: https://opae.github.io/latest/docs/pyopae/README.html
       - OPAE Plugin Developers Guide: sw/fpga_api/plug_guide/readme.md
    - OPAE LIBRARIES:
      - OPAE C API Reference: https://opae.github.io/latest/docs/fpga_api/fpga_api.html
      - OPAE C++ Core API Reference: https://opae.github.io/latest/docs/fpga_api/fpga_cxx_api.html
      - OPAE Python API Reference: https://opae.github.io/latest/docs/fpga_api/fpga_python_api.html
      - OPAE Plugin Developers Guide: sw/fpga_api/plug_guide/readme.md
    - OPAE LINUX KERNEL DRIVERS:
       - Open Programmable Accelerator Engine (OPAE) Linux Device Driver Architecture: sw/drv_arch/drv_arch.md
    - OPAE FPGA TOOLS:
       - fpgaconf: sw/fpga_tools/fpgaconf/fpgaconf.md
       - fpgainfo: sw/fpga_tools/fpgainfo/fpgainfo.md
       - fpgasupdate: sw/fpga_tools/fpgasupdate/fpgasupdate.md
       - mmlink: sw/fpga_tools/mmlink/mmlink.md
       - packager: sw/fpga_tools/packager/packager.md
       - userclk: sw/fpga_tools/userclk/userclk.md
       - hssi: sw/fpga_tools/hssi/hssi.md
       - pci_device: sw/fpga_tools/pci_device/pci_device.md
       - opae.io: sw/fpga_tools/opae.io/opae.io.md
       - rsu: sw/fpga_tools/rsu/rsu.md
       - host_exerciser: sw/fpga_tools/host_exerciser/host_exerciser.md
       - HSSI ethernet statistics: sw/fpga_tools/hssi_ethernet/hssistats.md
       - HSSI ethernet mac: sw/fpga_tools/hssi_ethernet/hssimac.md
       - HSSI ethernet loopback: sw/fpga_tools/hssi_ethernet/hssiloopback.md
       - mem_tg: sw/fpga_tools/mem_tg/mem_tg.md
       - vabtool: sw/fpga_tools/vabtool/vabtool.md
       - opaevfio: sw/fpga_tools/opaevfio/opaevfio.md
       - ofs.uio: sw/fpga_tools/ofs.uio/ofs.uio.md
       - opaeuio: sw/fpga_tools/opaeuio/opaeuio.md
       - fpgad: sw/fpga_tools/fpgad/fpgad.md
       - fpgadiag: sw/fpga_tools/fpgadiag/README.md

markdown_extensions:
  - md_in_html
  - abbr
  - attr_list
  - def_list
  - tables
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
env:          
  D5005_DEVICE: Intel® Stratix 10® FPGA
  D5005_BOARD: Intel® FPGA PAC D5005
  D5005_OFS_VER: 2022.3
  D5005_OFS_RELEASE: ofs-d5005-1.0.1
  D5005_OFS_TAG: ofs-d5005-1.0.1
  D5005_OFS_COMMON_RELEASE: ofs-fim-common-1.1.0-rc2
  D5005_OFS_AFU_EXAMPLE_TAG: ofs-examples-afu-1.0.0-rc3
  D5005_OFS_AFU_BBB_TAG: 1.0.0-rc3
  D5005_FIM_REPO: ofs-d5005
  D5005_FIM_TAG: release/1.0.x
  D5005_NIOS_FW_VER: 2.0.13
  D5005_BMC_RTL_BUILD_VER: 2.0.13
  D5005_QUARTUS_PRIME_PRO_VER: 22.3
  D5005_OS_VER: RHEL 8.2
  D5005_PYTHON_VER: 3.7.7
  D5005_CMAKE_VER: 3.11.4
  D5005_GCC_VER: 7.2.0
  D5005_GIT_VER: 1.8.3.1
  D5005_PERL_VER: 5.8.8
  D5005_OPAE_VER: 2.3.0-1
  D5005_OPAE_RELEASE: release/2.3.0
  D5005_KERNEL_VER: 5.15-lts
  D5005_KERNEL_VER_COMPLETE: 5.15.77
  D5005_KERNEL_BRANCH: ofs-2022.3-2
  D5005_BITSTREAM_ID: 0x401000287428628
  D5005_PR_ID: d51533ad-aee6-5dab-80fb-a44bbf579b68
  OFS_COMMON_BRANCH: ofs-fim-common
  OFS_COMMON_TAG: release/1.0.x

