# Copyright © 2016-2023 Martin Donath
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.


site_name: OFS
repo_url: https://github.com/OFS/
repo_name: ofs

theme:
  name: material
#  custom_dir: "overrides"
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs

    - content.code.copy
    - content.tooltips
    - search.suggest
    - search.highlight

# Page tree
nav:
  - Welcome: 'index.md'
  - Stratix 10 OFS Hardware Docs:
      - Quick Start Evaluation Guide: 'hw/d5005/user_guides/ug_eval_ofs_d5005/ug_eval_script_ofs_d5005.md'
      - Getting Started: 'hw/d5005/user_guides/ug_qs_ofs_d5005/ug_qs_ofs_d5005.md'
      - Software Reference Manual: 'hw/common/reference_manual/ofs_sw/mnl_sw_ofs.md'
      - FPGA Interface Manager Technical Reference Manual: 'hw/d5005/reference_manuals/ofs_fim/mnl_fim_ofs_d5005.md'
      - FPGA Interface Manager Developer Guide: 'hw/d5005/dev_guides/fim_dev/ug_dev_fim_ofs_d5005.md'
      - AFU Developer Guide: 'hw/d5005/dev_guides/afu_dev/ug_dev_afu_d5005.md'
  - OFS Software:
    - OPAE USER GUIDES:
       - Quick Start Guide: sw/fpga_api/quick_start/readme.md
       - OPAE Installation Guide: sw/install_guide/installation_guide.md
       - OPAE C API Programming Guide: sw/fpga_api/prog_guide/readme.md
       - OPAE Python Bindings: https://opae.github.io/latest/docs/pyopae/README.html
       - OPAE Plugin Developers Guide: sw/fpga_api/plug_guide/readme.md
    - OPAE LIBRARIES:
      - OPAE C API Reference: https://opae.github.io/latest/docs/fpga_api/fpga_api.html
      - OPAE C++ Core API Reference: https://opae.github.io/latest/docs/fpga_api/fpga_cxx_api.html
      - OPAE Python API Reference: https://opae.github.io/latest/docs/fpga_api/fpga_python_api.html
      - OPAE Plugin Developers Guide: sw/fpga_api/plug_guide/readme.md
    - OPAE LINUX KERNEL DRIVERS:
       - Open Programmable Accelerator Engine (OPAE) Linux Device Driver Architecture: sw/drv_arch/drv_arch.md
    - OPAE FPGA TOOLS:
       - fpgaconf: sw/fpga_tools/fpgaconf/fpgaconf.md
       - fpgainfo: sw/fpga_tools/fpgainfo/fpgainfo.md
       - fpgasupdate: sw/fpga_tools/fpgasupdate/fpgasupdate.md
       - mmlink: sw/fpga_tools/mmlink/mmlink.md
       - packager: sw/fpga_tools/packager/packager.md
       - userclk: sw/fpga_tools/userclk/userclk.md
       - hssi: sw/fpga_tools/hssi/hssi.md
       - pci_device: sw/fpga_tools/pci_device/pci_device.md
       - opae.io: sw/fpga_tools/opae.io/opae.io.md
       - rsu: sw/fpga_tools/rsu/rsu.md
       - host_exerciser: sw/fpga_tools/host_exerciser/host_exerciser.md
       - HSSI ethernet statistics: sw/fpga_tools/hssi_ethernet/hssistats.md
       - HSSI ethernet mac: sw/fpga_tools/hssi_ethernet/hssimac.md
       - HSSI ethernet loopback: sw/fpga_tools/hssi_ethernet/hssiloopback.md
       - mem_tg: sw/fpga_tools/mem_tg/mem_tg.md
       - vabtool: sw/fpga_tools/vabtool/vabtool.md
       - opaevfio: sw/fpga_tools/opaevfio/opaevfio.md
       - ofs.uio: sw/fpga_tools/ofs.uio/ofs.uio.md
       - opaeuio: sw/fpga_tools/opaeuio/opaeuio.md
       - fpgad: sw/fpga_tools/fpgad/fpgad.md
       - fpgadiag: sw/fpga_tools/fpgadiag/README.md

plugins:
  - mkdoxy:
      projects:
        opae-code:
          src-dirs: "/home/IOFS_BUILD_ROOT/opae-sdk/"
          full-doc: True
          doxy-cfg:
            FILE_PATTERNS: "*.c *.cc *.cxx *.cpp *.c++ *.java *.h *.hh *.hxx *.hpp *.h++ *.xpm *.md"
            EXAMPLE_PATH: ""
            RECURSIVE: True
            EXCLUDE_SYMLINKS: True
            EXCLUDE_PATTERNS: "*/archive/* */.git/*"

        opae-doc:
          src-dirs: "/home/IOFS_BUILD_ROOT/opae-sdk/doc/src"
          full-doc: True          
          doxy-cfg:
            FILE_PATTERNS: "*.c *.cc *.cxx *.cpp *.c++ *.java *.h *.hh *.hxx *.hpp *.h++ *.xpm *.md *.rst"
            EXTRACT_ALL: True
            EXAMPLE_PATH: ""
            INPUT_ENCODING: "UTF-8"
            RECURSIVE: True
            EXCLUDE_SYMLINKS: True
            EXCLUDE_PATTERNS: "*/archive/* */.git/*"




markdown_extensions:
  - attr_list
  - md_in_html
  - abbr
  - pymdownx.snippets
  - admonition
  - def_list
  - tables 

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:ofs.github@intel.com


